:global:
  componentName: openshift4-local-storage
  githubUrl: https://github.com/appuio/component-openshift4-local-storage
  feature_goldenTests: true

docs/antora.yml:
  name: openshift4-local-storage
  title: openshift4-local-storage
